#!/bin/bash

source ~/.secrets

MAIN_FOLDER="$HOME/Pictures/Screenshots"

FULL_MONTH=$(date +'%B')
FULL_YEAR=$(date +'%Y')

HOUR=$(date +'%H')
MINUTE=$(date +'%M')
SECOND=$(date +'%S')

DAY=$(date +'%d')
MONTH=$(date +'%m')
YEAR=$(date +'%y')

FILE_NAME="${HOUR}-${MINUTE}-${SECOND}-${MONTH}-${DAY}-${YEAR}"
FOLDER_NAME="$FULL_YEAR/$FULL_MONTH"

# Make folder(s)
mkdir -p ${MAIN_FOLDER}/${FOLDER_NAME}

# Take Screenshot
FLAGS="-rb"
if [[ "$1" != "" ]]; then FLAGS="-ab"; else FLAGS="-rb"; fi
spectacle ${FLAGS} -no ${MAIN_FOLDER}/${FOLDER_NAME}/${FILE_NAME}.png

if [ ! -e ${MAIN_FOLDER}/${FOLDER_NAME}/${FILE_NAME}.png ]; then exit 0; fi

# Send Uploading Notification
NOTIFICATION_ID=$(/usr/bin/notify-send -a DCS -t 0 -p "Uploading" "Screenshot is being uploaded")

# Upload file to custom api
UPLOAD=`curl -X POST -s ${PERSONAL_API_HOST}/v1/images/upload -H "authorization:${PERSONAL_API_INTERNAL_SECRET}" -F file=@${MAIN_FOLDER}/${FOLDER_NAME}/${FILE_NAME}.png`

# Check for an error and set the variables if so
ERROR_CODE=$(echo $UPLOAD | jq -r .code)
ERROR_MSG=$(echo $UPLOAD | jq -r .message)
HAS_ERROR=$([[ $ERROR_CODE != "null" && $ERROR_MSG != "null" ]] && echo "true" || echo "false")

if [[ $HAS_ERROR == "true" ]]; then
	/usr/bin/notify-send -a DCS -t 2000 -r ${NOTIFICATION_ID} "Error Uploading" "${ERROR_MSG}"; exit 0
fi

# Get file url
FILE_URL=$(echo $UPLOAD | jq -r .data.url)

# Copy URL to clipboard
if [[ $XDG_SESSION_TYPE == "wayland" ]]; then
	echo -n $FILE_URL | wl-copy
else
	echo -n $FILE_URL | xsel -i -b
fi

# Send Upload Notification
/usr/bin/notify-send -a DCS -t 1500 -r ${NOTIFICATION_ID} "Uploaded" "${FILE_URL}"
