#!/bin/bash

source ~/.secrets

MAIN_FOLDER="$HOME/Pictures/Screenshots"

FULL_DAY=$(date +'%A')
FULL_MONTH=$(date +'%B')
FULL_YEAR=$(date +'%Y')

HOUR=$(date +'%H')
MINUTE=$(date +'%M')
SECOND=$(date +'%S')

DAY=$(date +'%d')
MONTH=$(date +'%m')
YEAR=$(date +'%y')

FILE_NAME="${HOUR}-${MINUTE}-${SECOND}-${MONTH}-${DAY}-${YEAR}"
FOLDER_NAME="$FULL_YEAR/$FULL_MONTH/$FULL_DAY"

# Make folder(s)
mkdir -p ${MAIN_FOLDER}/${FOLDER_NAME}

# Take Screenshot
FLAGS="-r"
if [[ "$1" != "" ]]; then FLAGS="-ws"; else FLAGS="-rs"; fi
xfce4-screenshooter ${FLAGS} ${MAIN_FOLDER}/${FOLDER_NAME}/${FILE_NAME}.png

if [ ! -e ${MAIN_FOLDER}/${FOLDER_NAME}/${FILE_NAME}.png ]; then exit 0; fi

# Send Uploading Notification
NOTIFICATION_ID=$(/usr/bin/notify-send -a DCS -t 0 -p "Uploading" "Screenshot is being uploaded")

# Upload file to custom api
UPLOAD=`curl -X POST -s ${PERSONAL_API_HOST}/v1/images/upload -H "authorization:${PERSONAL_API_INTERNAL_SECRET}" -F file=@${MAIN_FOLDER}/${FOLDER_NAME}/${FILE_NAME}.png`

# Get file url
FILE_URL=$(echo $UPLOAD | jq -r .data.url)

# Copy URL to clipboard
echo -n $FILE_URL | xsel --input --clipboard
echo -n $FILE_URL | xsel

# Send Upload Notification
/usr/bin/notify-send -a DCS -t 1500 -r ${NOTIFICATION_ID} "Uploaded" "${FILE_URL}"