[General]
frontend=widgetsboxmodel
hotkey=Meta+Ctrl+Alt+Shift+Space
notifiedUnsupportedHotkey=false
runEmptyQuery=false
showTray=false
telemetry=false
terminal=Kitty

[applications]
enabled=true
fuzzy=true
ignore_show_in_keys=false
use_exec=false
use_generic_name=false
use_keywords=false

[calculator_qalculate]
enabled=true

[datetime]
enabled=true

[files]
enabled=false
paths=@Invalid()

[hash]
enabled=false

[path]
enabled=true

[pluginregistry]
global_handler_enabled=false
trigger_handler_enabled=false

[qmlboxmodel]
windowPosition=@Point(899 391)

[ssh]
enabled=false

[system]
enabled=true

[terminal]
enabled=false

[urlhandler]
enabled=false

[websearch]
enabled=false
fallback_hanlder_enabled=false

[widgetsboxmodel]
alwaysOnTop=true
clearOnHide=false
clientShadow=true
displayScrollbar=false
followCursor=false
hideOnFocusLoss=true
historySearch=true
itemCount=5
quitOnClose=false
showCentered=true
showFallbacksOnEmpty=true
systemShadow=true
theme=Spotlight Dark
windowPosition=@Point(927 391)
